//
//  ListRepositoriesViewControllerTests.swift
//  ItauChallenge
//
//  Created by Vinicius Custodio on 24/07/20.
//  Copyright (c) 2020 Vinicius Custodio. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ItauChallenge
import XCTest

class ListRepositoriesViewControllerTests: XCTestCase {

    // MARK: Subject under test
    var sut: ListRepositoriesController!
    var window: UIWindow!

    // MARK: Test lifecycle
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupListRepositoriesViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup
    func setupListRepositoriesViewController() {
        let bundle = Bundle.main
        sut = (UIStoryboard(name: "ListRepositories", bundle: bundle).instantiateViewController(withIdentifier: "ListRepositories") as! ListRepositoriesController)

    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }


    // MARK: Tests
    func testLoadRepoWhenViewIsLoaded() {
        // Given
        let mock = MockListRepositoriesBusinessLogic()
        sut.interactor = mock

        // When
        loadView()

        // Then
        XCTAssertTrue(mock.loadRepo)
    }

    func testSelectRepo() {
        // Given
        let mock = MockListRepositoriesBusinessLogic()
        sut.interactor = mock

        // When
        loadView()
        sut.tableView(sut.tableView, didSelectRowAt: IndexPath(item: 0, section: 0))

        // Then
        XCTAssertTrue(mock.selectRepo)
    }
}

// MARK: Test doubles
class MockListRepositoriesBusinessLogic: ListRepositoriesBusinessLogic {
    var loadRepo: Bool = false
    var selectRepo: Bool = false

    func loadRepositories(_ request: ListRepositories.LoadPage.Request) {
        loadRepo = true
    }

    func didSelectRepository(at index: Int) {
        selectRepo = true
    }


}
